modLoader="javafml"
loaderVersion="[25,)" #mandatory (24 is current forge version)
license = "All Rights Reserved"
[[mods]]
modId="out_of_sight"
version="${file.jarVersion}"
displayName="Out of Sight"
authors="Corosus"
description='''
Helps improve frame rates by limiting how far away tile entities and entities can render, with configurable ranges.
'''

[[dependencies.out_of_sight]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.44,)"
    ordering="NONE"
    side="CLIENT"